# Generated by Django 5.1.2 on 2024-10-24 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=600)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('profilepicture', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('candm', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('location', models.CharField(max_length=45)),
                ('isopen', models.BooleanField()),
                ('languages', models.CharField(blank=True, max_length=45, null=True)),
                ('maxsize', models.IntegerField()),
                ('dmneeded', models.BooleanField()),
                ('groupchatcontent', models.TextField(blank=True, null=True)),
                ('gameid', models.ForeignKey(db_column='gameid', on_delete=django.db.models.deletion.DO_NOTHING, to='TTRPGLFG.game')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('starttime', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('groupid', models.ForeignKey(db_column='groupid', on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.group')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Grouptag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.ForeignKey(db_column='groupid', on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.group')),
                ('tagid', models.ForeignKey(db_column='tagid', on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.tag')),
            ],
            options={
                'db_table': 'grouptag',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.user')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Belongsto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isowner', models.BooleanField()),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('groupid', models.ForeignKey(db_column='groupid', on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.group')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.user')),
            ],
            options={
                'db_table': 'belongsto',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('appchatcontent', models.TextField(blank=True, null=True)),
                ('groupid', models.ForeignKey(db_column='groupid', on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.group')),
                ('applicantid', models.ForeignKey(db_column='applicantid', on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.user')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Usertag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islooking', models.BooleanField()),
                ('tagid', models.ForeignKey(db_column='tagid', on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.tag')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.user')),
            ],
            options={
                'db_table': 'usertag',
            },
        ),
    ]
