# Generated by Django 5.1.3 on 2024-12-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTRPGLFG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chattype', models.CharField(choices=[('APP', 'application'), ('GRP', 'group')], default='APP', max_length=3)),
                ('applicationid', models.ForeignKey(db_column='applicationid', null=True, on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.application')),
                ('groupid', models.ForeignKey(db_column='groupid', null=True, on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.group')),
            ],
        ),
        migrations.CreateModel(
            name='Chatmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('chatmessagetype', models.CharField(choices=[('TXT', 'text'), ('SCD', 'schedule'), ('PRF', 'prefs')], default='TXT', max_length=3)),
                ('content', models.CharField(max_length=600)),
                ('chatid', models.ForeignKey(db_column='chatid', on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.chat')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='TTRPGLFG.user')),
            ],
        ),
    ]
