# Generated by Django 5.1.3 on 2024-12-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TTRPGLFG', '0002_chat_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='appchatcontent',
        ),
        migrations.RemoveField(
            model_name='group',
            name='groupchatcontent',
        ),
    ]
