# Generated by Django 5.1.3 on 2024-12-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTRPGLFG', '0003_remove_application_appchatcontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='belongsto',
            name='isdm',
            field=models.BooleanField(default=False),
        ),
    ]
